version: 0.0
os: linux

# Files to copy from build artifact to EC2
files:
  - source: /
    destination: /var/www/html/SampleTest/dotnet

# Hooks to run scripts during deployment
hooks:
  BeforeInstall:
    - location: scripts/cleanup_old_app.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_app.sh
      timeout: 300
      runas: root

