version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/SampleTest/dotnet

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      runas: root
  ValidateService:
    - location: scripts/validate_app.sh
      runas: root

