version: 0.0
os: linux
files:
  - source: publish/
    destination: /var/www/html/SampleTest/dotnet  # <- must exist or CodeDeploy must have permissions to create
hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user

