version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/SampleTest
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/stop_nginx.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 60
      runas: root

