version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - "echo '=== Starting INSTALL phase ==='"
      - "echo 'Current directory:' && pwd"
      - "echo 'Listing files:' && ls -R"
      - "echo 'Checking .NET SDK:'"
      - dotnet --info
      - "echo 'Restoring project dependencies:'"
      - dotnet restore SampleTest/dotnet/SampleTestApp.csproj --verbosity detailed

  build:
    commands:
      - "echo '=== Starting BUILD phase ==='"
      - dotnet publish SampleTest/dotnet/SampleTestApp.csproj -c Release -o ./publish
      - "echo 'Build complete. Contents of publish folder:'"
      - ls -R ./publish

artifacts:
  base-directory: publish
  files:
    - '**/*'

