version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Install phase"
      - dotnet --info
      - ls -R

  pre_build:
    commands:
      - echo "Restore phase"
      - dotnet restore "Sample Test.sln" --verbosity detailed 2>&1 | tee restore.log
      - echo "=== END RESTORE LOG ==="
      - cat restore.log

  build:
    commands:
      - echo "Build phase"
      - dotnet publish SampleTest.csproj -c Release -o publish
      - echo "=== Publish Output ==="
      - ls -R publish

artifacts:
  files:
    - appspec.yml
    - '**/*'
  base-directory: .
