version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Restoring .NET dependencies..."
      - dotnet restore SampleTest/SampleTestApp.csproj
  build:
    commands:
      - echo "Building project..."
      - dotnet publish SampleTest/SampleTestApp.csproj -c Release -o ./publish

artifacts:
  files:
    - publish/**/*
  base-directory: publish

