version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7.0
    commands:
      - echo "Checking .NET version"
      - dotnet --version
      - echo "Restoring NuGet packages..."
      - dotnet restore "Sample Test/dotnet/SampleTestApp.csproj"

  build:
    commands:
      - echo "Building the project..."
      - dotnet build "Sample Test/dotnet/SampleTestApp.csproj" --configuration Release
      - dotnet test "Sample Test/tests/SampleTestApp.Tests.csproj" --no-build --verbosity normal

artifacts:
  files:
    - "Sample Test/dotnet/**/*"
    - "Sample Test/scripts/**/*"
  discard-paths: no

