version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Install phase"
      - dotnet --info
      - ls -R

  pre_build:
    commands:
      - echo "Restore phase"
      - dotnet restore "Sample Test.sln" --verbosity detailed

  build:
    commands:
      - echo "Build phase"
      - dotnet publish SampleTest.csproj -c Release -o publish

artifacts:
  base-directory: publish
  files:
    - '**/*'

