version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI
      - npm install -g @angular/cli

  pre_build:
    commands:
      - echo Installing project dependencies
      - npm install

  build:
    commands:
      - echo Building Angular app
      - ng build --prod

artifacts:
  files:
    - dist/**
  discard-paths: yes

