version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Current directory: $(pwd)"
      - echo "Listing files recursively:"
      - ls -R
      - echo "Checking .NET SDK version..."
      - dotnet --info
      - echo "Attempting dotnet restore..."
      - dotnet restore SampleTest/dotnet/SampleTestApp.csproj

  build:
    commands:
      - echo "Building project..."
      - dotnet publish SampleTest/dotnet/SampleTestApp.csproj -c Release -o ./publish

artifacts:
  files:
    - publish/**/*
  base-directory: publish
