version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "=== INSTALL PHASE ==="
      - echo "Current directory: $(pwd)"
      - echo "Listing files recursively:"
      - ls -R
      - echo "Check .NET version"
      - dotnet --info

  pre_build:
    commands:
      - echo "=== RESTORE PHASE ==="
      # List the dotnet folder to confirm files
      - ls -R SampleTest/dotnet
      # Restore solution (handle spaces with quotes)
      - dotnet restore "SampleTest/dotnet/Sample Test.sln" --verbosity detailed

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      # Publish project to ./publish folder
      - dotnet publish "SampleTest/dotnet/SampleTest.csproj" -c Release -o publish
      - echo "Publish folder content:"
      - ls -R publish

artifacts:
  files:
    - '**/*'
  base-directory: publish

