version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "=== INSTALL PHASE ==="
      - ls -R
      - dotnet --info
  pre_build:
    commands:
      - echo "=== RESTORE PHASE ==="
      - dotnet restore "Sample Test.sln" --verbosity detailed
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - dotnet publish "SampleTest.csproj" -c Release -o publish
      - ls -R publish
artifacts:
  base-directory: publish
  files:
    - '**/*'

